FROM eclipse-temurin:17-jdk

RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip && \
    unzip sonar-scanner-cli-*.zip && \
    mkdir -p /opt/sonar-scanner && \
    mv sonar-scanner-*/* /opt/sonar-scanner

ENV PATH="/opt/sonar-scanner/bin:$PATH"

WORKDIR /usr/src
